name: Deploy to GitHub Pages
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install || echo "No dependencies"

      - name: Prepare build folder
        run: |
          mkdir build
          cp index.html build/ || echo "index.html not found"
          cp src/v86.js build/ || echo "v86.js not found"
          cp src/v86.wasm build/ || echo "v86.wasm not found"
          cp -r bios build/ || echo "bios/ not found"
          cp -r images build/ || echo "images/ not found"
          cp -r lib build/ || echo "lib/ not found"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
